model:
  name: lstm
  params:          
    hidden_size: 128
    num_layers: 2
    dropout: 0.3
  train_params:    
    epochs: 50
    lr: 0.001
    batch_size: 256

data:
  processed_dir: data/processed

output:
  dir: models